"""The bundled, verified source catalog (generated by tools/verify_catalog.py)."""

from __future__ import annotations

import json
from importlib import resources
from typing import Any


def load_catalog() -> dict[str, Any]:
    text = resources.files(__name__).joinpath("sources.json").read_text(encoding="utf-8")
    return json.loads(text)
